#!/bin/sh
if [ ! $1 ] ; then
    dir=/home/$(sbin/user)
elif [ $(echo $1 | cut -c 1) = "/" ] ; then
    dir=$1
else
    dir=$(sbin/pwd)/$1
fi
[ ! -d $(sbin/gametosys $dir) ] && echo "No such directory" && exit 1
[ "$(sbin/isx $dir)" = "1" ] && echo "Permission denied" && exit 1
echo $dir > etc/wd
