#!/bin/sh
[ ! $1 ] && echo "Missing operand" && exit 1
[ "$(sbin/isx $1)" = "1" ] && echo "Permission denied" && exit 1
file=$(sbin/readlink $1)
[ -d $file ] && echo "Is a directory" && exit 1
shift
./$file $@
